# Window

WINDOW_WIDTH = 800 
WINDOW_HEIGHT = 600
WINDOW_HALF_WIDTH = WINDOW_WIDTH / 2
WINDOW_HALF_HEIGHT = WINDOW_HEIGHT / 2
WINDOW_TITLE = "Mechanical Watches"
FPS = 60

# Watches

WATCHES_BG_RADIUS = WINDOW_HALF_HEIGHT * 0.9
SECONDS_HAND_LENGTH = WATCHES_BG_RADIUS
MINUTES_HAND_LENGTH = WATCHES_BG_RADIUS
HOURS_HAND_LENGTH = WATCHES_BG_RADIUS * 0.6

SECONDS_HAND_DEGREES_STEP = 6
MINUTES_HAND_DEGREES_STEP = 6
HOURS_HAND_DEGREES_STEP = 15

SECONDS_HAND_THICKNESS = 3
MINUTES_HAND_THICKNESS = 6
HOURS_HAND_THICKNESS = 9

# Colors

YELLOW_COLOR = (255, 255, 0)
RED_COLOR = (255, 0, 0)
GREEN_COLOR = (0, 255, 0)
BLUE_COLOR = (0, 0, 255)
PINK_COLOR = (255, 51, 241)
