WINDOW_WIDTH = 800 
WINDOW_HEIGHT = 600
WINDOW_HALF_WIDTH = WINDOW_WIDTH / 2
WINDOW_HALF_HEIGHT = WINDOW_HEIGHT / 2
WINDOW_TITLE = "Mechanical Watches"
FPS = 1

# Colors

YELLOW_COLOR = (255, 255, 0)
RED_COLOR = (255, 0, 0)
